name = "sqlite-dev"
type = "javascript"
compatibility_date = "2022-01-11"
workers_dev = true

[durable_objects]
bindings = [{ name = "DATABASE", class_name = "Database" }]

[build]
command = "./build.sh"

[build.upload]
format = "modules"
dir = "./dist"
main = "./worker.js" # becomes "./src/worker.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[[build.upload.rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]

[[migrations]]
tag = "v1"
new_classes = ["Database"]
